### ISSUE TITLE
Docs reference add-admin which no longer exists due to add-user being created

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#143]
The natlas-server README discusses using `add-admin.py` to add an admin user when now you need to run `add-user.py` with the `--admin` flag. This needs to be changed and reflected in the README.

**Comment by tophertimzen** [comment]
Furthermore, documentation on adding a user should be added to the README as well since we now have the functionality for it with `add-user.py`.

**Comment by 0xdade** [comment]
add-user should only be used in limited circumstances for bootstrapping purposes. It prints user passwords to the terminal and there is currently no way to force a password change on login. It is for initial bootstrapping only and the normal registration/invitation flow should be used wherever possible.

**Comment by 0xdade** [comment]
Updated `natlas-server/README.md` in db2700485f9b25c429e2547d36adc5ec3a29a818 to reference `add-user.py` instead of `add-admin.py` and indicated the need for the flag. I'm still going to refrain from suggesting anyone add users via the script, at least until I can implement a "force password change on next login" feature.
