### ISSUE TITLE
Export IP Addresses with Tags

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#259]
**Is your feature request related to a problem?**

Right now we have a few export options for a search result. We can export IP Addresses, and export IP Address with Scan ID. I want an easy export that includes the tags for each scan. 

**Describe the feature you'd like**

Include a way to export tags with the search results for a set of scans. Can likely introduce a new param `includeTags` much like scanIDs is `includeScanIDs`.

**Have you considered alternative ways to get this feature**

No

**Additional context**

N/A

**Comment by 0xdade** [comment]
Will not be introducing a new param for this. At this point it may be easier to provide the same interface but instead of a ton of duplicate `include<Blank>` params, have a single `include=` that takes a list of items from the document schema and includes them in the response.


`natlas.io/search?query=https&format=hostlist&include=ip,scan_id,tags`

something like that.

**Comment by 0xdade** [comment]
I'm actually going to go ahead and close this in favor of using the json export capability that already exists. `natlas.io/search?query=https&format=json` will give you the json representation of every host, which includes all the data that could possibly be exported. It'll mean having to parse the json instead of parsing line by line, but jq is prominent enough that I don't consider this a significant problem.
