### ISSUE TITLE
Add link to service from /host

### ISSUE THREAD

**Issue by tophertimzen** [natlas/natlas#30]
It would be awesome if within `/host?h=IP` you were able to click a link that took you to the service if it is on a known port like 80/443/etc.

**Comment by tophertimzen** [comment]
Well, when you click on a host it would be neat if I could just click on a port/address and not have to copy/paste/type port information into my browser.

**Comment by 0xdade** [comment]
While I agree that this would be convenient, it also adds risk to the user. Forcing someone to type it in manually means they are _slightly_ more likely to pay attention to where they are going and from where. Plus right now the "ports" field is stored as a single string, which means I would need to parse the string for the individual ports that you might want to click on (and then what do we do to determine which ports should be clickable? if nmap says it's http? if it's 80/443/8080/8443?). Going to close this for now as I don't think it's something that's going to be implemented unless you can convince me otherwise.
