### ISSUE TITLE
UserDocs on special scenario

### ISSUE THREAD

**Issue by zer010bs** [natlas/natlas#372]
**Is your feature request related to a problem?**
not a problem in terms of "issue" but a problem in terms of "know how to do it"

**Describe the feature you'd like**
i have a very special requirement why i'd use natlas, that is distributed non-intrusive vuin-scan with custom nse-scripts that should be triggered mostly automatically, with changing scopes. every scan has a different scope.

workflow is as follows:

- get a list of possibly affected ips, range 1k up to millions
- scale up natlas-agents on demand (terraform)
- feed the list as scope
- feed a custom nse-script to the agents
- perform the scan
- fetch results and analyse offsite
- delete scope

if such would be possible, i'd like to (basically) know how and deliver userdocs for given scenraio

**Have you considered alternative ways to get this feature**

yes. parallelizing nmap-scans ist the fastes way to achieve this

**Additional context**

**Comment by 0xdade** [comment]
I wouldn't necessarily consider this a very unique use case. This sounds like pretty much every bug hunter's use case. However, I don't believe that Natlas is the right tool for the job, for the following reasons:

1) Supplying custom scripts to agents must be done out of band, as the agents are defensive against a malicious server and if the server could deploy custom scripts then what we'd have is basically a botnet that only knows how to use lua.

2) Scope is changing every run, which means you're looking for a point in time assessment specific to that vulnerability. Natlas is a continuous recon platform that is meant to run mostly against the same set of targets (or a set of targets that has small additions and exclusions over time).

3) You're already fetching the results and scanning off-site, which, when combined with the scope changing every run, means you get no benefit from storing the data in elastic or being able to search the data in elastic.

Natlas is not currently in the business of being a vulnerability detection platform. While many of its designs may, on the surface, look like it's good for hunting specific vulnerabilities, that is simply not the case. It is a continuous reconnaissance platform, which can sometimes be used to find vulnerabilities in targets you care about.

I've thought about building a separate version of natlas that is entire server managed and allows for things like custom nse scripts, but that still wouldn't address the fundamental misalignment in the "scope changes with every scan" and "spin up, do scan, spin down" operating modes.

I'm sure there are other orchestration tools out there that'll let you do what you want, and if not then you could probably accomplish it pretty straight forward with terraform, ssh, and [nmap+logstash](https://www.elastic.co/blog/using-nmap-logstash-to-gain-insight-into-your-network). Given your existing monitoring tooling, I'm sure you're no stranger to building these types of things. I just don't think Natlas is the right tool for the job at this point in time.

**Comment by zer010bs** [comment]
thanks for clarifying. 

we (as in company) started experimenting with distributed nmap/message-queues/scheduling, but then came across natlas and thought i'd give it a try.

will still use this to see if this can be a usefull addition to our inhouse ASM-tool/recon we run for clients.

**Comment by 0xdade** [comment]
If I were building a ground up platform where I know I'll always have complete control of the workers and of the orchestrator, then I'd probably use a redis queue and have all of the workers spin up and talk to redis on launch. A simple python worker that wraps subprocess calls to nmap would get most of the way there, especially if you're running in a trusted network or an overlay network where you don't have to worry about authentication between worker and server.

We've been separating individual components out where possible, so if you want to do scan order randomization you could use our [cyclicprng](https://github.com/natlas/cyclicprng) combined with the the code in the [app/scope](https://github.com/natlas/natlas/tree/main/natlas-server/app/scope) module (which is not separated out at this time). That would give you the ability to canonically order a list of ip addresses and then iterate over them in a pseudo-random order. I have some interest in creating a standalone scope manager microservice that you may find useful, however we're still debating it a little bit.

We also have a defused version of [libnmap](https://github.com/natlas/natlas-libnmap) if you'd like to do xml parsing of the results (though I haven't given much attention to this lately other than making the fork of it, stripping it down and defusing it).

For huge amounts of addresses, especially if you only need to look for a couple specific ports, I'd recommend you group hosts together when you issue scans to the nmap process. Natlas currently only ever does one host at a time (partially due to wanting to store the raw output files of each scan individually) per scan thread, and it's actually a significant bottleneck for scaling due to the increased costs associated with frequently reinitializing the NSE.

**Comment by 0xdade** [comment]
All that said, hypothetically if I was going to use the current Natlas platform to do something like what you said, it'd look something like this:

>get a list of possibly affected ips, range 1k up to millions

This is entirely your responsibility to supply, not related to our scan orchestration.

>scale up natlas-agents on demand (terraform)

This is also a pre-step that natlas has no capability for. Terraform to spin up nodes, install docker and pull the agent down, then launch would probably not be that difficult, but is not something that Natlas currently supports. It is at this stage that I would also include the custom nse scripts in the templates.

> feed the list as scope

This can be accomplished through the `./add-scope.py` script that exists in natlas-server.

> feed a custom nse-script to the agents

You'll have to out-of-band feed the nse-scripts to the agents. I do this with an older managed deployments by simply using some ssh automation to scp the custom script to all of my agents and then adding the script name to the list of scripts running in the server config. See [the nmap docs](https://nmap.org/book/man-nse.html) for information about where you can put custom scripts to have them executed, but remember that your agents are in docker containers so you need to mount things in.

> perform the scan

This is what natlas already does so no problems here, except that there's no cycle-stop in natlas, it'll run forever if you let it and agents keep asking for work, which may not be what you want given this workflow.

> fetch results and analyse offsite

In versions from the last 5 months, the `/search` endpoint has supported a query parameter `format=json` which returns search results in their json format. This can be iterated to get a complete export of everything that matches your search. If you need a generic search that returns everything, "nmap" is in every single document.

> delete scope

You'd need to make a copy of the `./add-scope.py` script and instead of importing scope, you'd want to go through and delete them all. A quick and dirty way to do it is actually just `flask shell` followed by `ScopeItem.query.delete()` and `db.session.commit()`. However this will probably not cascade the delete to associated tags, and will create weird behaviors if you plan to use tags at all. There's no function on the model for this right now, but here's what the code in the admin panel looks like:

https://github.com/natlas/natlas/blob/06f1f35aa52450388af9f2a401246a4d08d16d8d/natlas-server/app/admin/routes.py#L242-L246

Hope this helps, though I suspect it will probably just further show the difficulties in using natlas for this purpose at this time.

**Comment by zer010bs** [comment]
since you answered detailed, i will give some context and an outlook what road we will probably go.

context: we are providing CVE-monitoring/alerting for CERTs and SOCs: workflow is
- CVE/alert comes in
- OSINT delivers data (thus the ever-changing scope)
- we check if non-intrusive scan is possible or not (here comes in the need for NSE)
- custom NSE is to enhance SNR / reduce FP as much as possible, whenever a non_intrusive check is possible
- depending on the size of the targets to be scanned, we fire up scanners to get the task done in 4-6hrs, rather than 24hrs or more
- for what we have tested so far, python/libnmap and converting xml-results into json just worked fine, the results then get feeded into a notification-pipeline that send out alerts to CERTs and such

rogue master is not of an issue, since the infa/system is usually shot down and will only get fired up when a job has to be done, so what we have in mind is more like a fire-and-forget - system with the ability to scale up scanning-nodes for faster results

for the message-queue: we will not use redis, because you will get jobs lost. a message-queue in a asynchronus system should handle/hand out jobs, and if they are not completed within a certain timeframe, e.g. the node working on that job failed/staled, should be able to re-issue that job again. message-brokers can handle this requirements just fine

the "master" on our side will 
- take the scope/list of IPs
- group them into packages
- look how many packages are there for the job
- decide how many scanning_nodes are needed
- fill the message_queue with jobs
- fire up nodes from templates to do the jobs in a given time. 

for 100k IPs i'd need ~10 nodes to have the job done in under 4 hours, which is ok and quite cheap.

long story short: i think there is room for an additional distributed nmap-scanner for our special needs :D
