### ISSUE TITLE
payload

### ISSUE THREAD

**Issue by mikeleib** [natlas/natlas#44]
server can offer client as a payload.  This ought to be protected with some secret, even if shared.  Expectation is client can `curl | python`

**Comment by 0xdade** [comment]
Due to the additional complexities of the agent and the increased dependencies for building a good data set, this won't be particularly reasonable. The agent already needs python3, pip3, virtualenv, a series of python packages, chromium-browser (for aquatone), unzip, xvfb-run, vncsnapshot, and aquatone. Maybe we can revisit this later, but as of now it's unattainable due to the shift in the direction that the project has taken.
