### ISSUE TITLE
Elastic index_not_found when Natlas is set up before ElasticSearch has been installed.

### ISSUE THREAD

**Issue by rosswsnider** [natlas/natlas#82]
After installing and configuring natlas, and calling its getwork API, natlas threw an exception that no correct elasticsearch index was found. To reproduce the issue:
1. Install the environment (python3, pip, virtualenv, etc) but do not install elasticsearch
2. Configure the flask variables in .env
3. ./setup-server.sh
4. ./run-server.sh

Back out of the running Natlas instance (after adding scope) and install elasticsearch (per the steps in the README.md).

When ./run-server.sh is activated again, call into natlas with `curl localhost:5000/api/getwork`

I get the following stack dump and exception:

> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/ubuntu/natlas/natlas-server/app/api/routes.py", line 34, in getwork
>     count, context = current_app.elastic.gethost_scan_id(rand)
>   File "/home/ubuntu/natlas/natlas-server/app/elastic.py", line 56, in gethost_scan_id
>     "query_string": {'query': scan_id, "fields": ["scan_id"], "default_operator": "AND"}}, "sort": {"ctime": {"order": "desc"}}})
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
>     return func(*args, params=params, **kwargs)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 660, in search
>     doc_type, '_search'), params=params, body=body)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
>     status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
>     self._raise_error(response.status, raw_data)
>   File "/home/ubuntu/.local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
>     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
> elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')

**Comment by 0xdade** [comment]
This breaks down to roughly two issues:

1.  We can't getwork if no elastic indexes have been defined, because we can't check our scan id against the existing scan ids.
2. Once we programmatically create indexes if none exist, we won't be able to do a sort on "ctime" because there will be no documents in the index and therefore no mapping for what "ctime" is. 

We might be able to address both of these at once by having our index creations include some mapping definitions. I'll need to look into it further.

**Comment by 0xdade** [comment]
The dirty hacks to get around this issue and get started, instead of waiting for me to commit a patch:

1. `curl -X PUT localhost:9200/nmap && curl -X PUT localhost:9200/nmap_history`
2. Make sure you have a scope and a service file defined on the server, then run `./natlas-agent.py --target <a target that's in scope>` and the agent will grab the service file, scan the target, and submit the results to the server. This will create a document in both indexes so that we can sort by "ctime"
